[project]
name = "configure-queue"
authors = ["configure-queue-dev"]
description = "A smart contract for managing configurable queues with token-based prioritization"
telemetry = false
requirements = []
[contracts.queue-manager]
path = "contracts/queue-manager.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
